required_players: 2
countdown-seconds: 15
game-time: 300
bungeecord: false
fallback-servers:
  - "1"
spawn:
  world: "world"
  x: 0
  y: 64
  z: 0
  yaw: 0
  pitch: 90
arenas:
  0:
    world: "world"
    x: 16
    y: 69
    z: 32
    yaw: 0
    pitch: 90
    # FIRST MAP
    1:
      world: "world"
      x: 16
      y: 70
      z: 32
      yaw: 0
      pitch: 90
    # IF SCOREBOARD WILL BE GREATER THAN 15 LINES, THE LINES AFTER 15 WILL BE REMOVED.
# IF TAB PLUGIN FROM NEZNAMY WAS NOT FOUND,
# YOU CAN ENABLE OR DISABLE CUSTOM SCOREBOARD FROM THIS PLUGIN
scoreboard-enabled: true
# TITLE OF SCOREBOARD
scoreboard-displayname: "&c&lFALLGUYS"
scoreboard:
  - "&aThis is custom scoreboard from"
  - "&cFallGuys"
tablist-enabled: true
tablist-header:
  - ""
  - ""
tablist-footer:
  - ""
  - ""